services:
  mtgsearch-bot:
    build: .
    command: gunicorn --workers=2 main:flask_app -b 0.0.0.0:3001
    volumes:
        - .:/code
    ports:
        - 3001:3001
    restart: "unless-stopped"
    depends_on:
        - db
  db:
    image: "postgres:14.2"
    container_name: mtgsearch-db
    restart: "unless-stopped"
    expose:
      - 5432
    volumes:
            - mtgsearch_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: "slackapp"
volumes:
  mtgsearch_postgres_data:
