ez = {'type': 'block_actions',
      'user': {'id': 'U073DF4CU8M', 'username': 'ezequiel', 'name': 'ezequiel', 'team_id': 'T0731REUKSB'},
      'api_app_id': 'A073DG1QV5K', 'token': 'LlvDabgT8i2t5DudsBdKLzKC',
      'container': {'type': 'view', 'view_id': 'V074B5Y7Q00'},
      'trigger_id': '7109856407047.7103864971895.fa3fcd2af9fe4f1e6a26a8fdf8ea249e',
      'team': {'id': 'T0731REUKSB', 'domain': 'thinkmartellworkspace'}, 'enterprise': None,
      'is_enterprise_install': False, 'view': {'id': 'V074B5Y7Q00', 'team_id': 'T0731REUKSB', 'type': 'modal',
                                               'blocks': [{'type': 'image', 'block_id': 'nhtWi',
                                                           'image_url': 'https://cards.scryfall.io/small/front/e/e/ee856e7a-37ee-435c-80e8-d0ac6f15892f.jpg?1627711045',
                                                           'alt_text': 'Forest',
                                                           'title': {'type': 'plain_text', 'text': 'Forest',
                                                                     'emoji': True}, 'image_width': 146,
                                                           'image_height': 204, 'image_bytes': 10916,
                                                           'is_animated': True, 'fallback': '146x204px image'},
                                                          {'type': 'actions', 'block_id': 'k3j5R', 'elements': [
                                                              {'type': 'button', 'action_id': 'Random',
                                                               'text': {'type': 'plain_text', 'text': 'Shuffle',
                                                                        'emoji': True}, 'value': 'default'}]}],
                                               'private_metadata': "{'channel': 'C073G92FCKV', 'card': 'ee856e7a-37ee-435c-80e8-d0ac6f15892f'}",
                                               'callback_id': '', 'state': {'values': {}},
                                               'hash': '1715811366.fscdVW1r',
                                               'title': {'type': 'plain_text', 'text': 'Random Card', 'emoji': True},
                                               'clear_on_close': False, 'notify_on_close': False,
                                               'close': {'type': 'plain_text', 'text': 'Cancel', 'emoji': True},
                                               'submit': {'type': 'plain_text', 'text': 'Post', 'emoji': True},
                                               'previous_view_id': None, 'root_view_id': 'V074B5Y7Q00',
                                               'app_id': 'A073DG1QV5K', 'external_id': '',
                                               'app_installed_team_id': 'T0731REUKSB', 'bot_id': 'B07325SSKHV'},
      'actions': [
          {'action_id': 'Random', 'block_id': 'k3j5R', 'text': {'type': 'plain_text', 'text': 'Shuffle', 'emoji': True},
           'value': 'default', 'type': 'button', 'action_ts': '1715811402.694019'}]}
